### ISSUE TITLE
请看看 x-cmd，看能否协同 ？

### ISSUE THREAD

**Issue by edwinjhlee** [ipconfiger/ru-cdc#1]
朋友，我今天在 头条 看到你的 项目简介。

如果你喜欢命令行，可以看看 我的项目:  [x-cmd.com](https://x-cmd.com/pkg/usql)
你可以理解 x-cmd 是一个 posix shell 的库 再加上一个 勿需sudo即可使用的 软件包 管理器。
现在 x-cmd 还没有公测，不过是足够稳定用于试用。

我今天看到 你的项目，我对 mysql 及其 生态 不是很了解 -- 所以也不是很了解cdc工具的使用场景。
不过非常欢迎 你的项目能够发版，并加入到 x-cmd/pkg 得到更好的传播。

**Comment by ipconfiger** [comment]
我觉得加入这个可能更适合：https://github.com/ipconfiger/ru-http-sync

**Comment by edwinjhlee** [comment]
好的，我们调研一下。
预祝你 新年快乐 ～

---

其实 http server 一项，caddy、python -m HTTPSERVER, 还有 nginx，都可以做到类似的功能 -- 我们 x-cmd 后面会引入 nginx pkg （portable） 以及 nginx 模块用来封装 常用部署脚本。nginx portable 的体积其实很小。

不过，很有可能 我对你的项目了解不深。这个容我年后仔细看看。

---

相对来说，我觉得 你的 ru-cdc 可能更有特殊价值。虽然面向人群相对更小，但是可能在该领域可以用 rust 在 效率 做到 顶尖。但我对 mysql 领域不熟了，后面我再找个时间深入调研一下。
rust 在这方面 优势是有了，相比 canal，体积就已经是个巨大优势。
